<center>

## ENSE 350 – Math Programming for Software Engineers - Laboratory

# Lab 2: GCD and Pulverizer

### University of Regina
### Faculty of Engineering and Applied Science - Software Systems Engineering
### Lab Instructor: [Adam Tilson](mailto:Adam.Tilson@uregina.ca)

</center>

## Introdcution

In this lab we will play a bit in python, to get you more familiar with the language, as well as thinking about factors. We will approach some problems with a poor solution (i.e. brute-force), before employing more clever ways to approach the problem, which you will implement in the lab assignment.

## Part 1: Quick Python Review

Let's do a quick review of some elements of Python which will be useful in this lab - functions, loops and lists

Write code which prints out all odd numbers from `22` to `33`, inclusive:

In [3]:
printOddInts(22,33)

23
25
27
29
31
33


Write a function which prints out all odd numbers from `n` to `m`, inclusive:

In [2]:
def printOddInts(n,m):
    for i in range(n, m+1):
        if i % 2 == 1:
            print(i)

Write a function called `get_list_of_odds(n, m)` which returns a list of odd numbers between n and m, inclusive:

Using the function created, get the list of odds from `22` to `33`, inclusive:

## Part 2: Factors

Let's look at some math and examples of factors:

Consider the number `333`. Using python, create a list which contains all of the factors of this number:

In [1]:
for i in range (1, 333+1):
    if 333 % i == 0:
        print(i)

1
3
9
37
111
333


Consider the number `3034`. Using python, create a list which contains all of the factors of this number:

In [5]:
for i in range (1, 3034+1):
    if 3034 % i == 0:
        print(i)

1
2
37
41
74
82
1517
3034


What is the largest factor in common between `333` and `3034` (also known as the Greatest Common Divisor, or GCD)?

In [ ]:
37

Create a function called `get_list_of_factors(a)` which returns the a list of factors of a number, `a`

In [6]:
def getListOfFactors(a):
    listOfFactors = []
    for i in range (1, a+1):
        if a % i == 0:
            listOfFactors.append(i)
    return listOfFactors

In [7]:
getListOfFactors(3034)

[1, 2, 37, 41, 74, 82, 1517, 3034]

Create a function called `get_largest_number_in_both_lists(list_a, list_b)` which finds the largest number which exists in both lists:

In [16]:
def getLargestNum(listA, listB):
    listA.sort()
    listB.sort()
    listA.reverse()
    for entry in listA:
        if entry in listB:
            return entry
    
    

# Part 3: The GCD (Poor Solution)

Using the functions created so far, create a function called `brute_force_gcd(a,b)` which computes the gcd between `a` and `b` by brute force

In [14]:
def bruteForceGCD(a,b):
    getListOfFactorsA = getListOfFactors(a)
    getListOfFactorsB = getListOfFactors(b)
    gcd = getLargestNum(getListOfFactorsA, getListOfFactorsB)
    return gcd

Compute the GCD between `333` and `3034`:

In [15]:
bruteForceGCD(333, 3034)

37

Estimate how many lines of code ran to figure out this GCD:

In [18]:
333 + 3034 + 6*8

3415

Estimate how many lines of code if we ran this, for, say `51324` and `123457`

In [20]:
51324 + 123457 + 10*20

174981

Cool, that seems pretty bad!

What would that factor be?

In [21]:
bruteForceGCD(51324, 123457)

1

When the greatest common factor between two numbers is `1`, those numbers are called `relatively prime`.

## Part 4: The GCD (A Better Approach)

We have seen our brute force algorithm is not great, especially for larger numbers. What else can we do?

Enter the `Euclidean Algorithm`:

```
    gcd(a,b) = gcd(b, a%b)
```

Where `a%b` is the reminder when `a` is divided by `b`

This algorithm has an approximate runtime of $O(log_2(n))$

Using the brute-force method we previously implemented, find the GCD between `899` and `493`?

In [23]:
bruteForceGCD(899, 493)

29

Verify this result is correct by applying the Euclidean Algorithm

### Use this cell to work through the Euclidean Algorithm

```
gcd (a, b) = gcd (b, a%b)
gcd (899, 493) = gcd (493, 406)
gcd (493, 406) = gcd (406, 87)
gcd (406, 87) = gcd (87, 58)
gcd (87, 58) = gcd (58, 29)
gcd (58, 29) = gcd (29, 0)
STOP
```

In [31]:
#gcd (899, 493) = gcd (493, 899%493) = gcd (493, 406)
#gcd(493, 406) = gcd(493, 493%406) = gcd (406, 87)
#gcd(406, 87) = gcd(87, 406%87) = gcd (87, 58)
#gcd(87, 58) = gcd (58, 87%58) = gcd (58, 29)
#gcd(58, 29) = gcd (58, 58%29) = gcd (29, 0)
#STOP
#gcd = 29

print(899%493)
print(493%406)
print(406%87)
print(87%58)
print(58%29)

406
87
58
29
0


Hint, `gcd (a, 0) = a`, because ALL numbers divide `0`, (i.e. `0 = 0*a`)

## Part 5: The GCD (An Extended Approach)

Another unique property of the GCD algorithm is that it satisfies the following equation:

```
    gcd(a,b) = sa + tb
```

Where `s` and `t` are coefficients, with positive or negative values, that when multiplied by `a` and `b` respectively, then sum together, produce the `gcd` of `a` and `b`.

So, with our example of `gcd(899,493)`, we know there exists some `s` and `t` such that:

```
gcd(899,493) = s * 899 + t * 493
29 = s * 899 + t * 493
```

In the RSA algorithms, which we will see next week, we will see that these residual values are particularly useful.

To find these values, we employ the pulverizer. This tabular approach to the GCD keeps track of some intermediate values as we work to discover the final values.

### Let's do this on the `board`!

So from this work, we can see that 

```
gcd(899,493) = s * 899 + t * 493
29 = s * 899 + t * 493
29 = -6 * 899 + 11 * 493
```

FAQ:
- Why do you use the variables `x` and `y` instead of `a` and `b`?
    - I like to use `a` and `b` to represent the original numbers we are attempting to find the GCD of. `x` and `y` change from row to row, but `a` and `b` do not. Recall that in each row we are rewriting the equation in terms of the original `a` and `b`.


- How do I program this?
    - I find the easiest way to implement is to use represent the table using a list of a built-in python data structures. Which data structure might be useful to keep track of a row of different values, e.g. an `x`, `y`, `quot`, `rem`, `s` and `t`? Try using code to generate only the first row or two of the list, then try to turn it into a looping (or recursive) algorithm. Once the process terminates and the list is generated correctly, then it's simply a matter of returning the correct values from the data structure.
    
An interesting observation can be made when we look at the relationship between the values in this table. This observation is useful in implementing a highly optimized version of this algorithm, or in getting started with an iterative approach: